# Generated by Django 3.2.21 on 2023-10-09 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0003_auto_20231009_2222'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Prestamos',
            new_name='Prestamo',
        ),
    ]
